-- =============================================================================
-- Refund drawer attribution (2026-07-25).
--
-- A CASH refund physically leaves a receptionist's drawer, so their shift tally
-- must drop by it. Until now day_cash_tally() attributed the deduction to
-- refunds.generated_by_id — whoever CLICKED "Refund". That is fine when the
-- receptionist refunds their own patient, but RECEPTION_ISSUE_REFUNDS is also
-- held by doctors and admins; when one of THEM issues the refund the deduction
-- landed on a person with no drawer, leaving the real receptionist short.
--
-- Fix: a new column paid_out_by_id records WHOSE DRAWER the cash came out of —
-- normally the receptionist who took the ORIGINAL payment (bills.paid_by_id),
-- collected minutes earlier. generated_by_id stays = the clicker (audit trail /
-- voucher "Generated by"). Non-cash refunds never touched a drawer, so they
-- stay NULL.
--
-- Backfill points every historic CASH refund at the original payer's drawer —
-- the correct attribution retroactively.
--
-- Idempotent: information_schema-guarded ADD COLUMN (shared MySQL lacks
-- ADD COLUMN IF NOT EXISTS). Run in phpMyAdmin against the HMIS database.
-- Safe to re-run. RUN BEFORE deploying the code that writes paid_out_by_id.
-- =============================================================================

DROP PROCEDURE IF EXISTS hims_add_refund_paid_out_by;
DELIMITER $$
CREATE PROCEDURE hims_add_refund_paid_out_by()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = DATABASE()
                     AND table_name = 'refunds'
                     AND column_name = 'paid_out_by_id') THEN
        ALTER TABLE refunds
            ADD COLUMN paid_out_by_id INT NULL AFTER generated_by_id,
            ADD CONSTRAINT fk_refunds_paid_out_by FOREIGN KEY (paid_out_by_id) REFERENCES users(id),
            ADD INDEX idx_refund_paid_out (paid_out_by_id);
    END IF;
END $$
DELIMITER ;

CALL hims_add_refund_paid_out_by();
DROP PROCEDURE IF EXISTS hims_add_refund_paid_out_by;

-- ---- Backfill: point historic CASH refunds at the original payer's drawer ----
-- Only cash refunds (the ones that moved a drawer) and only rows not already set.
UPDATE refunds r
JOIN bills b ON b.id = r.bill_id
SET r.paid_out_by_id = b.paid_by_id
WHERE r.paid_out_by_id IS NULL
  AND r.refund_mode = 'cash'
  AND b.paid_by_id IS NOT NULL;

-- ---- Verify (read-only) ----
-- Any cash refund still NULL here had no resolvable original payer — those keep
-- falling back to generated_by_id in the tally (COALESCE), unchanged behaviour.
SELECT refund_mode,
       COUNT(*)                                        AS refunds,
       SUM(paid_out_by_id IS NOT NULL)                 AS with_drawer
FROM refunds
GROUP BY refund_mode;
